mysite/descargas/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


app_name = 'descargas'
urlpatterns = [
    
    url(r'^descargas/facultad$', views.descargas, name='facultad'),
    url(r'^descargas/facultad/materia$', views.descargas_materia, name='materia'),
    
]

mysite/informacion/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


app_name = 'informacion'
urlpatterns = [
    
    url(r'^informacion/facultad/$', views.informacion, name='facultad'),
    
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from website import views as app_views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	
    #urls para autenticar via twitter
    url(r'^$', app_views.index, name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

	   #urls para la app principal 'website' van aca.
	url(r'^', include('website.urls')),
        #urls para la app de 'descargas' van aca.
    url(r'^', include('descargas.urls')),
        #urls para la app de 'informacion' van aca.
    url(r'^', include('informacion.urls')),
        #urls para la app de 'informacion' van aca.
    url(r'^', include('solicitudes.urls')),
]

mysite/solicitudes/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



app_name = 'solicitudes'
urlpatterns = [
    
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^sugerencia/$', views.sugerencia, name='sugerencia'),
    url(r'^pedir_asesoria/$', views.pedir_asesoria, name='asesoria'),
    url(r'^administrar/solicitudes/$', views.administrar_solicitudes, name='admin'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/$', views.solicitud_detalle ,name='solicitud_detalles'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/reservar$', views.solicitud_reservar ,name='solicitud_reservar'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/liberar$', views.solicitud_liberar ,name='solicitud_liberar'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/completa$', views.solicitud_completa ,name='solicitud_completa'),
]

mysite/website/urls.py
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url
from django.views.generic import TemplateView
from django.views.static import serve

from . import views

app_name = 'website'
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^registrar/$', views.registrar, name='registrar'),
    url(r'^logmein/$', views.logmein, name='logmein'),
    url(r'^logmeout/$', views.logmeout, name='logmeout'),
        
        #Views y urls para la recuperacion de passwords
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
  #  url(r'^desbloqueo/$', views.desbloquear_cuenta, name='desbloquear_cuenta'),
    url(r'^perfil/$', views.perfil, name='ver_perfil'),
    url(r'^perfil/editar$', views.perfil_editar, name='editar_perfil'),
    url(r'^opciones/$', views.opciones, name='opciones_perfil'),
    url(r'^opciones/password/$', views.password, name='cambiar_password'),
    url(r'^desbloquear/$', views.indicar_email, name='desbloquear_email'),
    url(r'^desbloquear/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.desbloquear_cuenta.as_view(), name='activate_account'),
]

# URL para servir las imagenes de forma local durante debug.

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT,}),
    ]

mysite/website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# Create your models here.

#Modelo para representar una facultad
class Facultad(models.Model):
	class Meta:
		verbose_name_plural = "facultades"

	nombre = models.CharField(max_length=50)

	def __str__(self):
		return self.nombre

#Modelo para representar escuelas de una facultad.
class Escuela(models.Model):

	nombre = models.CharField(max_length=50)
	facultad = models.ForeignKey(Facultad, blank=True, default=1)
	unique_together = (("nombre", "facultad"),)

	def __str__(self):
		return 'Escuela de %s, Facultad de %s' % (self.nombre, self.facultad ,)
		#return self.nombre

#Modelo para representar materias de una facultad.
class Materia(models.Model):

	SEMESTRES = (('electiva', 'Electiva'),('1', 'I'),('2', 'II'),('3', 'III'),('4', 'IV'),('5', 'V'),\
				('6', 'VI'),('7', 'VII'),('8', 'VIII'),('9', 'IX'),('10', 'X'))

	nombre = models.CharField(max_length=100)
	creditos = models.PositiveSmallIntegerField(default=0)
	codigo = models.PositiveSmallIntegerField()
	escuela = models.ForeignKey(Escuela, blank=True, default=1)
	semestre = models.CharField(max_length=10, choices=SEMESTRES, default='I')
	unique_together = (("codigo", "facultad"),)

	def __str__(self):
		return '%s: %s' % (self.nombre,self.escuela)

# Modelo para el perfil del usuario y otros atributos.
class Perfil(models.Model):

	PREGUNTAS = (('libro','¿Cual es tu libro infantil favorito?'),\
				 ('cancion','¿Cómo se llama tu canción favorita?'),\
				 ('abuelo','¿Cómo se llama tu abuelo paterno?'),\
				 ('abuela','¿Cómo se llama tu abuela materna?'),\
				 ('mascota','¿Como se llamaba tu primera mascota?'),\
				 ('auto','¿Cual es tu marca de autos preferida?'))

	class Meta:
		verbose_name_plural = "perfiles"

	user = models.OneToOneField(User, on_delete = models.CASCADE)
	cedula = models.CharField(max_length=20, unique=True, null=True, default=None)
	desc = models.TextField(max_length=500,default='' ,blank=True)
	foto = models.ImageField(blank=True, upload_to="user_avatars", default="user_avatars/default.gif")
		#preguntas y respuestas de seguridad.
	pregunta1 = models.CharField(max_length=15,choices=PREGUNTAS, default='libro')
	respuesta1= models.CharField(max_length=100,default='')
	pregunta2 = models.CharField(max_length=15,choices=PREGUNTAS, default='auto')
	respuesta2= models.CharField(max_length=100,default='')

	facultad = models.ForeignKey(Facultad, default=1)
	escuela = models.ForeignKey(Escuela,default=1)

	carrera = models.CharField(max_length=50,blank=True, default='')

	fallos_login = models.PositiveSmallIntegerField(default=0)
	esta_bloqueado = models.BooleanField(default=False)

	es_supervisor = models.BooleanField(default=False)

	materia = models.ForeignKey(Materia,blank=True, default = 1) #Materia que el usuario supervisor gestiona.

	#falta campo para una imagen del avatar del usuario
	
	def __str__(self):
		return 'Perfil del usuario: %s' % self.user.username

#esta seccion de codigo nos permite crear un modelo perfil
#por cada usuario creado en el sistema automaticamente.
def crear_perfil(sender, **kwargs):
	user = kwargs["instance"]
	if kwargs["created"]:
		user_profile = Perfil(user=user)
		user_profile.save()
		
post_save.connect(crear_perfil, sender=User)

mysite/website/views.py
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.db import connection, transaction
from django.http import HttpResponse
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.template import RequestContext, loader
from django.template.loader import render_to_string
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views import View
from social_django.models import UserSocialAuth
from .forms import LoginForm, CambiarPassForm, DefinirPassForm, RegisterPerfilForm, RegisterUserForm, RecuperarPassForm, EditarUserForm, EditarPerfilForm, PreguntasSecretasForm
from .models import Perfil
from .tokens import account_unlock_token



# Views de la app principal 'website' van aca.
def index(request):
	if request.user.is_authenticated:
		if request.user.perfil.es_supervisor:
			return render(request, 'website/index_user.html',{'base_template':'website/base_admin.html'})
		else:
			return render(request, 'website/index_user.html',{'base_template':'website/base_usuario.html'})
	else:
		loginf = LoginForm()	
		return render(request, 'website/index_noauth.html', {'loginf': loginf})

# View para autenticar usuarios e iniciar sesión
def logmein(request):
	
	form = LoginForm(request.POST or None)

	if request.POST and form.is_valid():
		user = form.login(request)
		if user:
			login(request, user)
			return redirect('website:home')
	return render(request, 'website/index_noauth.html', {'loginf': form })


# View para cerrar la sesión de usuarios
def logmeout(request):
	logout(request)
	return redirect('website:home')



# Vista que se encarga de el manejo de la edicion de los perfiles de usuario.
@login_required(login_url='/') 
def perfil_editar(request):
	
	if request.method == 'POST':
		uf = EditarUserForm(request.POST, request.FILES, instance=request.user,prefix='user')
		pf = EditarPerfilForm(request.POST, request.FILES, instance=request.user.perfil,prefix='perfil')
		if uf.is_valid() * pf.is_valid():
			uf.save()
			pf.save()
		return redirect('website:ver_perfil')

	user_form =	EditarUserForm(instance=request.user,prefix='user')
	perfil_form = EditarPerfilForm(instance=request.user.perfil,prefix='perfil')
	if request.user.perfil.es_supervisor:
		return render(request, 'website/perfil_editar.html',{'base_template':'website/base_admin.html', 'uf':user_form,'pf':perfil_form })
	else:
		return render(request, 'website/perfil_editar.html',{'base_template':'website/base_usuario.html', 'uf':user_form,'pf':perfil_form })

# View para desplegar el formulario de registro de usuarios y atender las peticiones de registro
def registrar(request):
	loginf = LoginForm()

	if request.method == 'POST':
		ruf = RegisterUserForm(request.POST, prefix='user')
		rpf = RegisterPerfilForm(request.POST, prefix='userprofile')
		if ruf.is_valid() * rpf.is_valid():
			user = ruf.save()
			userprofile = user.perfil

			userprofile.cedula = rpf.cleaned_data['cedula']
			userprofile.facultad = rpf.cleaned_data['facultad']
			userprofile.pregunta1 = rpf.cleaned_data['pregunta1']
			userprofile.respuesta1 = rpf.cleaned_data['respuesta1']
			userprofile.pregunta2 = rpf.cleaned_data['pregunta2']
			userprofile.respuesta2 = rpf.cleaned_data['respuesta2']
			userprofile.save()

			# Ahora una vez creado el usuario y su perfil procederemos a enviarle un mensaje
			# al email indicado con sus credenciales.
			context = {'username':ruf.cleaned_data['username'] ,'password':ruf.cleaned_data['password1']}
			
			msg_plain = render_to_string('registration/user_register_email.txt', context)
			msg_html = render_to_string('registration/user_register_email.html', context)
			
			send_mail(
					'Bienvenido a Foro-Estudiantil!', 	#titulo
					msg_plain,							#mensaje txt
					'foroestudiantil2@gmail.com',		#email de envio
					[user.email],						#destinatario
					html_message=msg_html,				#mensaje en html
					)

			
			return redirect('website:home')
		else:
			return render(request,'website/registrar.html', {'registeruserform':ruf, 'registerperfilform':rpf,'loginf': loginf})
	else:
		ruf = RegisterUserForm(prefix='user')
		rpf = RegisterPerfilForm(prefix='userprofile')
			#Si un usuario con sesión iniciada llega a esta página, se le cerrará la sesión.
		if request.user.is_authenticated:
			logout(request)

		return render(request, 'website/registrar.html', {'registeruserform':ruf, 'registerperfilform':rpf,'loginf': loginf})

# Vista para tomar el email del usuario y si existe buscar sus preguntas secretas en la base de datos
def indicar_email(request):
	loginf = LoginForm()

	if request.method == 'POST':
		emailform = RecuperarPassForm(request.POST or None)
		if emailform.is_valid():
			#Si el usuario es valido se procede a redibujar la pagina con las preguntas secretas correspondientes
			preguntasf = PreguntasSecretasForm()
			user = User.objects.get(email=emailform.cleaned_data['email'])
			
			return render(request, 'website/desbloquear_preguntas.html', {'userinf': user,'preguntasf':preguntasf, 'loginf':loginf})
		else:
			# Si no es un email valido se le indica al usuario.
			return render(request, 'website/indicar_email.html', {'emailf':emailform, 'loginf':loginf})
	
	emailform = RecuperarPassForm()
	return render(request, 'website/indicar_email.html', {'emailf':emailform, 'loginf':loginf})

class desbloquear_cuenta(View):

    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_unlock_token.check_token(user, token):
            login(request, user)
            return redirect('website:cambiar_password')
        else:
            # invalid link
            return render(request, 'registration/invalid.html')

	
@login_required(login_url='/') 
def perfil(request):
	contexto_comun = {'nombre': request.user.first_name,\
	  				   'apellido': request.user.last_name,\
	  				   'email': request.user.email,\
	  				   'facultad': request.user.perfil.facultad,\
	  				   'desc': request.user.perfil.desc,\
	  				   'base_template':'website/base_usuario.html'\
	  				  }

	contexto_admin = {'nombre': request.user.first_name,\
	  				   'apellido': request.user.last_name,\
	  				   'email': request.user.email,\
	  				   'facultad': request.user.perfil.facultad,\
	  				   'desc': request.user.perfil.desc,\
	  				   'base_template':'website/base_admin.html'\
	  				  }

	if request.user.perfil.es_supervisor:
		return render(request, 'website/perfil.html',contexto_admin)
	else:
		return render(request, 'website/perfil.html',contexto_comun)



@login_required
def opciones(request):
	user = request.user

	try:
		facebook_login = user.social_auth.get(provider='facebook')
	except UserSocialAuth.DoesNotExist:
		facebook_login = None

	can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

	if request.user.perfil.es_supervisor:
		return render(request, 'website/opciones.html',{'base_template':'website/base_admin.html','facebook_login': facebook_login,'can_disconnect': can_disconnect})
	else:
		return render(request, 'website/opciones.html',{'base_template':'website/base_usuario.html','facebook_login': facebook_login,'can_disconnect': can_disconnect})


@login_required
def password(request):
	if request.user.has_usable_password():
		PasswordForm = CambiarPassForm
	else:
		PasswordForm = DefinirPassForm

	if request.method == 'POST':
		form = PasswordForm(request.user, request.POST)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)

				#Envio de email con las nuevas credenciales al correo electrónico del usuario
			user = User.objects.get(pk=request.user.id)
			userprofile = Perfil.objects.get(user = user)
			context = {'username': user.username ,'password':form.cleaned_data['new_password1']}
			
			msg_plain = render_to_string('registration/user_pwdreset_email.txt', context)
			msg_html = render_to_string('registration/user_pwdreset_email.html', context)
			
			send_mail(
					'Cambio de Contraseña - Foro-Estudiantil!', #titulo
					msg_plain,									#mensaje txt
					'foroestudiantil2@gmail.com',				#email de envio
					[user.email],								#destinatario
					html_message=msg_html,						#mensaje en html
					)

				# Nos aseguramos siempre de desbloquar a un usuario despues de el cambio de contraseña
			userprofile.esta_bloqueado = False
			userprofile.save()

			return redirect('website:opciones_perfil')
	else:
		form = PasswordForm(request.user)

	if request.user.perfil.es_supervisor:
		return render(request, 'website/password.html',{'base_template':'website/base_admin.html','form': form})
	else:
		return render(request, 'website/password.html',{'base_template':'website/base_usuario.html','form': form})

mysite/website/templates/website/base_admin.html
{% load static %}
<!DOCTYPE html>
<!-- Autor: Rafael Vasquez -->
<html>
    <head>
        <title>
            {% block title %}{% endblock %}-Forum Estudiantil
        </title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
        <link href="{% static 'website/css/style.css' %}" type="text/css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Raleway|Roboto" rel="stylesheet">
        <!-- Libreria de jQuery y Bootstrap -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- Script personalizado-->
        <script type="text/javascript" src="{% static 'website/js/myjsscript.js' %}"></script>
    </head>
    <body class="admin">
        <!-----------------  Barra de Navegacion  ------------------>
        <nav id="myTopnav" class="topnav">
            <a href="{% url 'website:home' %}" class="left brand"><strong>Forum-Estudiantil</strong></a>
            <a href="{% url 'descargas:facultad' %}" class="left menu-link">Descargas</a>
            <a href="{% url 'informacion:facultad' %}" class="left menu-link">Informaci&oacute;n</a>
            <a href="{% url 'solicitudes:asesoria' %}" class="left menu-link">Asesoramiento</a>
            <a href="{% url 'solicitudes:sugerencia' %}" class="left menu-link">Sugerencias</a>
            <a href="{% url 'solicitudes:admin' %}" id="h-link-admin-sol" class="left menu-link invisible">Administrar Solicitudes</a>
            <a href="{% url 'website:ver_perfil' %}" id="h-link-perfil" class="left menu-link invisible">Mi perfil</a>
            <a href="{% url 'website:opciones_perfil' %}" id="h-link-perfil" class="left menu-link invisible">Opciones</a>
            <a href="{% url 'website:logmeout' %}" id="h-link-logout" class="left menu-link invisible">Cerrar Sesión</a>
            <a href="javascript:void(0);" class="icon" >&#9776;</a>
            <div class="clipfix">
            <ul class="nav navbar-nav pull-right nav-menu-options" id="menu-usuario">
                <li><img src=" {{ user.perfil.foto.url }}" class="hidden-xs hidden-sm nav-avatar"></li>
                <li><h4 class="user-name">{{ user.username }}</h4></li>
                <li class = "user-options-menu">
                    <div class="dropdown">
                        <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-menu-down"></span>
                        </button>
                        <ul class="dropdown-menu admin">
                            <li>
                                <a class="menu-link" href="{% url 'website:ver_perfil' %}">Mi Perfil <span class="glyphicon glyphicon-user"></span></a>
                            </li>
                            <li>
                                <a class="menu-link" href="{% url 'website:opciones_perfil' %}">Opciones <span class="glyphicon glyphicon-wrench"></span></a>
                            </li>
                            <li>
                                <a class="menu-link" href="{% url 'solicitudes:admin' %}">Administrar Solicitudes <span class="glyphicon glyphicon-envelope"></span></a>
                            </li>
                            <li>
                                <a class="menu-link" href="{% url 'website:logmeout' %}">Cerrar Sesi&oacute;n <span class="glyphicon glyphicon-log-out"></span></a>
                            </li>
                        </ul>
                    </div>
                </li>
    
            </ul>
            </div>
        </nav>
        <div class="relleno"></div>

        
        <!-------------------  Aca va el contenido ----------------- -->
        {% block content %}
        {% endblock %}

        <!-----------------  pie de pagina  ------------------>
        <footer>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-6 col-sm-5 col-sm-offset-1 col-md-4 col-md-offset-2 col-lg-4 col-lg-offset-2 col-xl-4 col-xl-offset-2 creditos">
                        <p> © 2017 Todos los derechos reservados.</p>
                        <p> Diseño y c&oacute;digo creados por Rafael Vasquez</p>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 col-lg-4 col-lg-offset-2 col-xl-4 col-xl-offset-2">
                        <a href="{% url 'solicitudes:contacto' %}" class="btn-contacto">Cont&aacute;ctanos</a>
                    </div>
                </div>
            </div>
        </footer>

    </body>
</html>

mysite/website/templates/website/base_usuario.html
{% load static %}
<!DOCTYPE html>
<!-- Autor: Rafael Vasquez -->
<html>
    <head>
        <title>
            {% block title %}{% endblock %}-Forum Estudiantil
        </title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> 
        <link href="{% static 'website/css/style.css' %}" type="text/css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Open+Sans|Raleway|Roboto" rel="stylesheet">
        <!-- Libreria de jQuery y Bootstrap -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- Script personalizado-->
        <script type="text/javascript" src="{% static 'website/js/myjsscript.js' %}"></script>
    </head>
    <body>
        <!-----------------  Barra de Navegacion  ------------------>
        <nav id="myTopnav" class="topnav">
            <a href="{% url 'website:home' %}" class="left brand"><strong>Forum-Estudiantil</strong></a>
            <a href="{% url 'descargas:facultad' %}" class="left menu-link">Descargas</a>
            <a href="{% url 'informacion:facultad' %}" class="left menu-link">Informaci&oacute;n</a>
            <a href="{% url 'solicitudes:asesoria' %}" class="left menu-link">Asesoramiento</a>
            <a href="{% url 'solicitudes:sugerencia' %}" class="left menu-link">Sugerencias</a>
            <a href="{% url 'website:ver_perfil' %}" id="h-link-perfil" class="left menu-link invisible">Mi perfil</a>
            <a href="{% url 'website:opciones_perfil' %}" id="h-link-perfil" class="left menu-link invisible">Opciones</a>
            <a href="{% url 'website:logmeout' %}" id="h-link-logout" class="left menu-link invisible">Cerrar Sesión</a>
            <a href="javascript:void(0);" class="icon" >&#9776;</a>
            <div class="clipfix">
            <ul class="nav navbar-nav pull-right nav-menu-options hidden-xs" id="menu-usuario">
                <li><img src=" {{ user.perfil.foto.url }}" class="hidden-xs hidden-sm nav-avatar"></li>
                <li><p class="user-name">{{ user.username }}</p></li>
                <li class = "user-options-menu">
                    <div class="dropdown">
                        <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-menu-down"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="menu-link" href="{% url 'website:ver_perfil' %}">Mi Perfil <span class="glyphicon glyphicon-user"></span></a></li>
                            <li><a class="menu-link" href="{% url 'website:opciones_perfil' %}">Opciones <span class="glyphicon glyphicon-wrench"></span></a></li>
                            <li><a class="menu-link" href="{% url 'website:logmeout' %}">Cerrar Sesi&oacute;n <span class="glyphicon glyphicon-log-out"></span></a></li>
                        </ul>
                    </div>
                </li>
    
            </ul>
            </div>
            
        </nav>
        <div class="relleno"></div>

        
        <!-------------------  Aca va el contenido ----------------- -->
        {% block content %}
        {% endblock %}

        <!-----------------  pie de pagina  ------------------>
        <footer>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-6 col-sm-5 col-sm-offset-1 col-md-4 col-md-offset-2 col-lg-4 col-lg-offset-2 col-xl-4 col-xl-offset-2 creditos">
                        <p> © 2017 Todos los derechos reservados.</p>
                        <p> Diseño y c&oacute;digo creados por Rafael Vasquez</p>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-sm-offset-2 col-md-4 col-md-offset-2 col-lg-4 col-lg-offset-2 col-xl-4 col-xl-offset-2">
                        <a href="{% url 'solicitudes:contacto' %}" class="btn-contacto">Cont&aacute;ctanos</a>
                    </div>
                </div>
            </div>
        </footer>

    </body>
</html>

mysite/website/templates/website/indicar_email.html
{% extends 'website/base.html' %}
{% load static %}

{% block title %}Indicar Email{% endblock %}

{% block content %}

	<h1> Desbloquear Cuenta </h1>
	<div class="container main-container">
		<div class="row login-form">
            <div class="col-md-10 col-md-offset-1">
                <h4>Intrucciones:</h4>
                <p class="instrucciones">
                    Por favor ingrese el correo electrónico asociado a su cuenta y posteriormente responda las preguntas secretas indicadas.
                </p>
                <form method="post" action="/desbloquear/">

                    {% csrf_token %} 

                    {% for field in emailf %}
                        <div class="form-group">
                            {{ field.label_tag }}<br>

                            {% if field.errors %}
                                <div class="form-errors">
                                {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                                </div>
                            {% endif %}

                            {{ field }}
                        </div>
                    {% endfor %}
                    
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-success btn-lg btn-block submit-btn">Siguiente</button>
                        </div>
                    </div>
                    
                </form>
            </div>
		</div>
	</div>

{% endblock %}