mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from website import views as app_views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	
    #urls para autenticar via twitter
    url(r'^$', app_views.index, name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

	   #urls para la app principal 'website' van aca.
	url(r'^', include('website.urls')),
        #urls para la app de 'descargas' van aca.
    url(r'^', include('descargas.urls')),
        #urls para la app de 'informacion' van aca.
    url(r'^', include('informacion.urls')),
        #urls para la app de 'informacion' van aca.
    url(r'^', include('solicitudes.urls')),
]

mysite/solicitudes/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



app_name = 'solicitudes'
urlpatterns = [
    
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^sugerencia/$', views.sugerencia, name='sugerencia'),
    url(r'^pedir_asesoria/$', views.pedir_asesoria, name='asesoria'),
    url(r'^administrar/solicitudes/$', views.administrar_solicitudes, name='admin'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/$', views.solicitud_detalle ,name='solicitud_detalles'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/reservar$', views.solicitud_reservar ,name='solicitud_reservar'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/liberar$', views.solicitud_liberar ,name='solicitud_liberar'),
    url( r'^administrar/solicitudes/(?P<id_sol>\d+)/completa$', views.solicitud_completa ,name='solicitud_completa'),
]

mysite/solicitudes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from website.models import Materia

# Create your models here.

#Modelo para representar las solicitudes de asesoría, contacto y sugerencias de los usuarios.
class Solicitud(models.Model):

	class Meta:
		verbose_name_plural = "solicitudes"

	ESTADOS = (('Libre','Libre'),('Pendiente','Pendiente'),('Atendida','Atendida'))
	TIPOS = (('Asesoría','Asesoría'),('Contacto','Contacto'),('Sugerencia','Sugerencia'))

	nombre = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	telefono = models.CharField(max_length=20, blank=True, default='')
	titulo = models.CharField(max_length=125)
	cuerpo = models.TextField(max_length=255)
	fecha_enviado = models.DateTimeField(_('Fecha Enviado'), default=timezone.now)
	supervisor = models.ForeignKey(User, blank=True, null=True, related_name='recipiente',limit_choices_to={'perfil__es_supervisor': True})
	user = models.ForeignKey(User,related_name='cliente', blank=True, null=True)
	materia = models.ForeignKey(Materia, blank=True, null=True)
	estado = models.CharField(max_length=15, choices=ESTADOS, default='Libre')
	tipo = models.CharField(max_length=15, choices=TIPOS, default='Asesoría')

	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return "%i/" % self.id

mysite/solicitudes/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Solicitud

# Formulario para realizar una solicitud de contacto.
class ContactanosForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(ContactanosForm, self).__init__(*args, **kwargs)
		self.fields['nombre'].widget = forms.TextInput(attrs={'class':'form-control','placeholder':'Nombre de contacto'})
		self.fields['email'].widget = forms.EmailInput(attrs={'class':'form-control', 'placeholder':'ejemplo@email.com'})
		self.fields['telefono'].widget = forms.TextInput(attrs={'class':'form-control','pattern':"\d{7,20}",'placeholder':'Teléfono de contacto sin espacios o guiones'})
		self.fields['titulo'].widget = forms.TextInput(attrs={'class':'form-control',})
		self.fields['cuerpo'].widget = forms.Textarea(attrs={'class':'form-control','placeholder':'Escriba su mensaje aquí'})
		



	class Meta:
		model = Solicitud
		fields = ['nombre','email','telefono','titulo','cuerpo']
		labels = { 'nombre': _('Nombre'),\
				   'email': _('Correo electrónico'),\
				   'telefono': _('Teléfono de contacto'),\
				   'titulo': _('Razón de contacto'),\
				   'cuerpo': _('Mensaje'),\
				 }

mysite/solicitudes/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from .forms import ContactanosForm
from .models import Solicitud
from website.forms import LoginForm

# Create your views here.

def contacto(request):
	if request.method == 'POST':
		cform = ContactanosForm(request.POST or None)
		if cform.is_valid():
			solicitud = cform.save(commit=False)
			solicitud.tipo = 'Contacto'
			solicitud.save()
			return redirect('website:home')
		return redirect('solicitudes:contacto')
	else:
		contactof = ContactanosForm()
		if request.user.is_authenticated:
			if request.user.perfil.es_supervisor:
				return render(request, 'solicitudes/contacto.html',{'base_template':'website/base_admin.html','contactof':contactof})
			else:
				return render(request, 'solicitudes/contacto.html',{'base_template':'website/base_usuario.html','contactof':contactof})
		else:			
			loginf = LoginForm()	
			return render(request, 'solicitudes/contacto.html', {'base_template':'website/base.html','loginf': loginf,'contactof':contactof})


@login_required(login_url='/') 
def pedir_asesoria(request):
	 
	if request.user.perfil.es_supervisor:
		return render(request, 'solicitudes/pedir_asesoria.html',{'base_template':'website/base_admin.html'})
	else:
		return render(request, 'solicitudes/pedir_asesoria.html',{'base_template':'website/base_usuario.html'})

@login_required(login_url='/') 
def sugerencia(request):
	if request.user.perfil.es_supervisor:
		return render(request, 'solicitudes/sugerencia.html',{'base_template':'website/base_admin.html'})
	else:
		return render(request, 'solicitudes/sugerencia.html',{'base_template':'website/base_usuario.html'})

@login_required(login_url='/')
def solicitud_detalle(request,id_sol):
	if request.user.perfil.es_supervisor:
		#Buscamos las solicitudes libres

		solicitud = get_object_or_404(Solicitud, pk=id_sol)
		#solicitud = Solicitud.objects.get(pk=id_sol)

		return render(request, 'solicitudes/solicitud_detalle.html', {'solicitud':solicitud})
	
	raise Http404("Esta página no existe")


@login_required(login_url='/')
def solicitud_reservar(request,id_sol):
	if request.user.perfil.es_supervisor:
		
			#Buscamos las solicitud indicada a reservar en la base de datos.
		solicitud = get_object_or_404(Solicitud, pk=id_sol)
		#solicitud = Solicitud.objects.get(pk=id_sol)

			#Asignamos el supervisor que la reservo directo a la solicitud
		solicitud.supervisor = request.user

			# y alteramos su estado.
		solicitud.estado = 'Pendiente'
		solicitud.save()
		return redirect('solicitudes:admin')
		#return render(request, 'solicitudes/solicitud_detalle.html', {'solicitud':solicitud})
	
	raise Http404("Esta página no existe")

@login_required(login_url='/')
def solicitud_liberar(request,id_sol):
	if request.user.perfil.es_supervisor:
		
			#Buscamos las solicitud indicada a liberar en la base de datos.
		solicitud = get_object_or_404(Solicitud, pk=id_sol)
		#solicitud = Solicitud.objects.get(pk=id_sol)

			#Desasignamos el supervisor de la solicitud
		solicitud.supervisor = None

			# y alteramos su estado.
		solicitud.estado = 'Libre'
		solicitud.save()
		return redirect('solicitudes:admin')
		#return render(request, 'solicitudes/solicitud_detalle.html', {'solicitud':solicitud})
	
	raise Http404("Esta página no existe")

@login_required(login_url='/')
def solicitud_completa(request,id_sol):
	if request.user.perfil.es_supervisor:
		
			#Buscamos las solicitud indicada a liberar en la base de datos.
		solicitud = get_object_or_404(Solicitud, pk=id_sol)
		#solicitud = Solicitud.objects.get(pk=id_sol)

			# y alteramos su estado.
		solicitud.estado = 'Atendida'
		solicitud.save()
		return redirect('solicitudes:admin')
		#return render(request, 'solicitudes/solicitud_detalle.html', {'solicitud':solicitud})
	
	raise Http404("Esta página no existe")


@login_required(login_url='/')
def administrar_solicitudes(request):

	if request.user.perfil.es_supervisor:
		#Buscamos las solicitudes libres

		libres = Solicitud.objects.filter(estado = 'Libre').order_by('fecha_enviado')
		pendientes = Solicitud.objects.filter(supervisor = request.user, estado = 'Pendiente').order_by('fecha_enviado')
		atendidas = Solicitud.objects.filter(supervisor = request.user, estado = 'Atendida').order_by('fecha_enviado')

		contexto = {'solLibres':libres, 'solReservadas': pendientes, 'solAtendidas': atendidas}
		return render(request, 'solicitudes/administrar_solicitudes.html',contexto)

	
	raise Http404("Esta página no existe")

mysite/solicitudes/templates/solicitudes/administrar_solicitudes.html
{% extends 'website/base_admin.html' %}
{% load static %}

{% block title %}Administrar Solicitudes{% endblock %}

{% block content %}
	
	<h1> Administrar Solicitudes </h1>
	<div class="jumbotron container">
		<h3 class="text-center sol-title">Mis solicitudes</h3>
		<hr>
		<br>
		<div class="row">
			<div class="col-md-12">
				<table id="t01">
					<tr>
						<th>Tema</th>
						<th>Mensaje</th>
						<th>Tipo</th>
						<th>Estado</th>
						<th>Fecha</th>
					</tr>

					{% for sol in solReservadas %}
						<tr class="pendiente">
							<td><a href="{{ sol.get_absolute_url }}">{{ sol.titulo|truncatewords:6 }}</a></td>
							<td>{{ sol.cuerpo|truncatewords:12 }}</td>
							<td>{{ sol.tipo }}</td>
							<td>{{ sol.estado }}</td>
							<td>{{ sol.fecha_enviado.day }}/{% if sol.fecha_enviado.month < 10 %}0{% endif %}{{ sol.fecha_enviado.month }}/{{ sol.fecha_enviado.year }}</td>
						</tr>
					{% endfor %}

					{% for sol in solAtendidas %}
						<tr>
							<td><a href="{{ sol.get_absolute_url }}">{{ sol.titulo|truncatewords:6 }}</a></td>
							<td>{{ sol.cuerpo|truncatewords:12 }}</td>
							<td>{{ sol.tipo }}</td>
							<td>{{ sol.estado }}</td>
							<td>{{ sol.fecha_enviado.day }}/{% if sol.fecha_enviado.month < 10 %}0{% endif %}{{ sol.fecha_enviado.month }}/{{ sol.fecha_enviado.year }}</td>
						</tr>
					{% endfor %}

				</table>

				{% if not solReservadas and not solAtendidas %}
					
					<h4 class="text-center" style = "color: red;">No hay solicitudes que desplegar.</h4>
					
				{% endif %}


			</div>
		</div>
		<div class="relleno"></div>
		<h3 class="text-center sol-title2">Solicitudes por Atender</h3>
		<hr>
		<br>
		<div class="row">
			<div class="col-md-12">
				<table id="t01">
					<tr>
						<th>Tema</th>
						<th>Mensaje</th>
						<th>Tipo</th>
						<th>Estado</th>
						<th>Fecha</th>
					</tr>
					{% for sol in solLibres %}
						<tr>
							<td><a href="{{ sol.get_absolute_url }}">{{ sol.titulo|truncatewords:6 }}</a></td>
							<td>{{ sol.cuerpo|truncatewords:12 }}</td>
							<td>{{ sol.tipo }}</td>
							<td>{{ sol.estado }}</td>
							<td>{{ sol.fecha_enviado.day }}/{% if sol.fecha_enviado.month < 10 %}0{% endif %}{{ sol.fecha_enviado.month }}/{{ sol.fecha_enviado.year }}</td>
						</tr>
					{% endfor %}
				</table>

			</div>
		</div>
	</div>

{% endblock %}

mysite/solicitudes/templates/solicitudes/contacto.html
{% extends base_template %}
{% load static %}

{% block title %}Contacto{% endblock %}

{% block content %}

	<h1> Cont&aacute;ctanos </h1>
	<div class="container main-container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<form method="post">

					{% csrf_token %} 
					<fieldset>
						<legend>Datos de Contacto</legend>
						{% for field in contactof %}
                            <div class="form-group">
                                {{ field.label_tag }}<br>

                                {% if field.errors %}
                                    <div class="form-errors">
                                    {% for error in field.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                    </div>
                                {% endif %}

                                {{ field }}
                            </div>
                        {% endfor %}
	                </fieldset>
	                <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-success btn-lg btn-block submit-btn">Contactar</button>
                        </div>
                    </div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}

mysite/solicitudes/templates/solicitudes/pedir_asesoria.html
{% extends base_template %}
{% load static %}

{% block title %}Solicitar Asesorías{% endblock %}

{% block content %}

	<h1> Solicitar Asesor&iacute;a </h1>
	<div class="container main-container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<form>
					<fieldset>
	                	<legend>Datos de la consulta</legend>
	                	<div class="form-group">    
	                        <label>Materia:</label>
	                        <input type="text" class="form-control" name="materia" required>
	                    </div>

	                    <div class="form-group">    
	                        <label>Tema:</label>
	                        <input type="text" class="form-control" name="tema" required>
	                    </div>
	                    <div class="form-group">
	                        <label>Duda:</label><br>
	                        <textarea id="mensaje" name="mensaje" placeholder="Escriba su mensaje aqu&iacute;.." style="height:200px; width: 100%"></textarea>
	                    </div>
	                </fieldset>
	                <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-success btn-lg btn-block submit-btn">Solicitar</button>
                        </div>
                     </div>
				</form>
			</div>
		</div>
	</div>


{% endblock %}

mysite/solicitudes/templates/solicitudes/solicitud_detalle.html
{% extends 'website/base_admin.html' %}
{% load static %}

{% block title %}Solicitud{% endblock %}

{% block content %}
	
	<div class="jumbotron container">

		{% if solicitud.tipo == 'Contacto' %}
			<h2 class="text-center">Solicitud de Contacto</h2>
			<hr>
			<div class="row">
				<div class="col-md-3 col-md-offset-1">
					<label>Nombre:</label>
					<p>{{ solicitud.nombre }}</p>
				</div>
				<div class="col-md-3 col-md-offset-1">

					<label>Teléfono:</label>
					{% if solicitud.telefono %}
						<p>{{ solicitud.telefono }}</p>
					{% else %}
						<p>Ninguno</p>
					{% endif %}
					
				</div>
				<div class="col-md-4">
					<label>Correo Eletrónico:</label>
					<p>{{ solicitud.email }}</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<label>Título:</label>
					<p>{{ solicitud.titulo }}</p>
					<label>Mensaje:</label>
					<p>{{ solicitud.cuerpo }}</p>
				</div>
			</div>
		{% endif %}

		<div class="relleno"></div>

		<div class="row">

			{% if solicitud.estado == 'Libre' %}
				<form class="col-md-6" action="{% url 'solicitudes:solicitud_reservar' solicitud.id %}">
					<div class="col-md-8 col-md-offset-2">
	                   <button type="submit" class="btn btn-success btn-lg btn-block submit-btn">Reservar <i class="fa fa-lock" style="font-size:24px"></i></button>
	                </div>

				</form>
				<form class="col-md-6">
					<div class="col-md-8 col-md-offset-2">
	                   <button type="submit" disabled class="btn btn-info btn-lg btn-block submit-btn">Atentida <i class="fa fa-check-circle" style="font-size:24px"></i></button>
	                </div>
				</form>
			{% elif solicitud.estado == 'Pendiente'%}
				<form class="col-md-6" action="{% url 'solicitudes:solicitud_liberar' solicitud.id %}">
					<div class="col-md-8 col-md-offset-2">
	                   <button type="submit" class="btn btn-primary btn-lg btn-block submit-btn">Liberar <i class="fa fa-unlock" style="font-size:24px"></i></button>
	                </div>

				</form>
				<form class="col-md-6" action="{% url 'solicitudes:solicitud_completa' solicitud.id %}">
					<div class="col-md-8 col-md-offset-2">
	                   <button type="submit" class="btn btn-info btn-lg btn-block submit-btn">Atentida <i class="fa fa-check-circle" style="font-size:24px"></i></button>
	                </div>
				</form>
			{% else %}
				<div class="col-md-8 col-md-offset-2">
					<h3 class="text-center" style = "color: red;">Esta solicitud ya ha sido atendida.</h3>
				</div>
			{% endif %}
		</div>
		

	</div>

{% endblock %}

mysite/solicitudes/templates/solicitudes/sugerencia.html
{% extends base_template %}
{% load static %}

{% block title %}Sugerencias{% endblock %}

{% block content %}

		<h1> Hacer una Sugerencia </h1>
		<div class="container main-container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<form>
					<fieldset>
	                	<legend>Datos de la sugerencia</legend>

	                    <div class="form-group">    
	                        <label>Tema:</label>
	                        <input type="text" class="form-control" name="tema" required>
	                    </div>
	                    <div class="form-group">
	                        <label>Sugerencia:</label><br>
	                        <textarea id="mensaje" name="mensaje" placeholder="Escriba su mensaje aqu&iacute;.." style="height:200px; width: 100%"></textarea>
	                    </div>
	                </fieldset>
	                <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <button type="submit" class="btn btn-success btn-lg btn-block submit-btn">Enviar</button>
                        </div>
                     </div>
				</form>
			</div>
		</div>
	</div>

{% endblock %}